In [ ]:
%reload_ext autoreload
%autoreload 2

In [1]:
print('hello zz')

hello


In [16]:
import os
print(os.getcwd())
sys.path.append('./Scheduler')
print(sys)
from data.loader import InstanceConfigLoader

/hdd/lsh
<module 'sys' (built-in)>


ModuleNotFoundError: No module named 'data.loader'

In [ ]:
import random

a = random.randint(1,10)
a

: 

In [2]:
from abc import ABC, abstractmethod


class Trigger(ABC):
    @abstractmethod
    def __call__(self, cluster, clock):
        pass


class ThresholdTrigger(Trigger):
    def __call__(self, cluster, clock, cpu_threshold=0.55, memory_threshold=0.55, disk_threshold=0.55):
        print(cluster,disk_threshold)

triger = ThresholdTrigger()
triger('1',2)

1 0.55


In [3]:
import random as rd
for i in  range(1,10):
    next = rd.randint(1,10)
    print(f'{i},next random in 1-10 is{next}')


1,next random in 1-10 is7
2,next random in 1-10 is10
3,next random in 1-10 is8
4,next random in 1-10 is3
5,next random in 1-10 is1
6,next random in 1-10 is3
7,next random in 1-10 is7
8,next random in 1-10 is7
9,next random in 1-10 is7


In [1]:
import sys
import os
print(os.getcwd())

/hdd/lsh/Scheduler/test


In [5]:
import numpy as np
cpulist = {1:[1,2,3],2:[1,2,3]}
cpu = np.array([v for k,v in cpulist.items()])
cpu.shape[0]
cpu = np.zeros(shape=(3,4))
cpu[0][1]=2
cpu

array([[0., 2., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
%reload_ext autoreload
%autoreload 2

## 测试添加machine

In [5]:
import json
import sys
sys.path.append('./Scheduler')
from data.loader import InstanceConfigLoader
from framework.algorithm import ThresholdFirstFitAlgorithm
#from framework.instance import InstanceConfig
from framework.machine import MachineConfig
from framework.simulation import Simulation
from framework.trigger import ThresholdTrigger

if __name__ == '__main__':
    instance_number = 20
    machine_number = int(instance_number/2+instance_number/4)
    machine_configs = []
    for id in range(machine_number):
        machine = MachineConfig(id,300,20,20)
        machine_configs.append(machine)
    macFile = '/Users/lsh/Documents/ecnuIcloud/Trace/alibaba_2018/intp_dir'
    windowsFile = 'D:\Data\workplace\ecnuicloud\Traces\intp_dir\\'
    linux_file = '/hdd/sxy/Trace_alibaba2018/alibaba_2018/intp_dir'
    instance_configs = InstanceConfigLoader(linux_file,instance_number)
    sim = Simulation(machine_configs, instance_configs, ThresholdTrigger(), ThresholdFirstFitAlgorithm())
    sim.run()

    #print(sim.cluster.structure)
    struct = sim.cluster.structure
    filename = './struct.json'
    with open(filename,'w') as file_job:
        json.dump(struct,file_job)


mac:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no schedule
no sche

In [25]:

env = simpy.Environment()
trigger = ThresholdTrigger()
trigger(cluster,env)
macid_to_schedule = []
insid_to_schedule=[]
for macid in cluster.machines_to_schedule:
    macid_to_schedule.append(macid.id)

instances_to_reschedule = [inst \
    for machine in cluster.machines_to_schedule \
        for inst in machine.instances.values()]
        
for ins in instances_to_reschedule:
    insid_to_schedule.append(ins.id)
print('machine id to schedule',macid_to_schedule)
print('instance id to schedule',insid_to_schedule)
# for instance, instance_cpu_curve in instance_cpu_curves.items():
#     print(instance.id,f'next is its type {type(instance_cpu_curve)} cpus:',\
#         instance_cpu_curve)
algorithm = ThresholdFirstFitAlgorithm()
algorithm(cluster,env)

machine id to schedule []
instance id to schedule []


TypeError: 'NoneType' object is not iterable

## 其他python测试

In [25]:
# python 类属性测试
class A:
    def __init__(self,name):
        self.name = name
    @property
    def cpu(self):
        return 2
    @property
    def test(self):
        return self.cpu
    def setName(self,name):
        self.name = name
    def algo(self):
        return 1,2,3
a,b,c =A('abc'),A('bcd'),A('eeee')
demo = [a,b,c]
for deo in demo:
    deo.name = 'change2'
print(a.name,b.name,c.name)
ares = a.algo()
ares[0]

change2 change2 change2


1

In [23]:
#test dict remove list
demo = {1:[1,2,3,4],
2:[1,2,3,4],
3:[1,2,3,4],
4:[1,2,3,4],
5:[1,2,3,4],
6:[1,2,3,4],
7:[1,2,3,4]}
print('lase: ',demo)
print('next:')
for key,value in demo.items():
    value.pop(1)
    # print(value)
    # demo[key]=value
print('new:',demo)
len(demo.items())
demo.get(2,None)

lase:  {1: [1, 2, 3, 4], 2: [1, 2, 3, 4], 3: [1, 2, 3, 4], 4: [1, 2, 3, 4], 5: [1, 2, 3, 4], 6: [1, 2, 3, 4], 7: [1, 2, 3, 4]}
next:
new: {1: [1, 3, 4], 2: [1, 3, 4], 3: [1, 3, 4], 4: [1, 3, 4], 5: [1, 3, 4], 6: [1, 3, 4], 7: [1, 3, 4]}


[1, 3, 4]

### 在for循环中remove

In [ ]:
def sq(x):
    return x*x

map(sq,[y for y in range(10)])

In [ ]:
# 字典排序测试
machines = cluster.machines

for k,v in machines.items():
    print('old:',k,v.cpu)
#对值排序
machines = {k:v for k,v in sorted(machines.items(),key= lambda x:x[1].cpu,reverse=True)}
for k,v in machines.items():
    print(v.cpu)
# machine_id = [ids for ids,cpu in machine_id_cpu.itms()]
# print('after sort:',machine_id)


In [7]:
# 集合添加 测试

def mylist_toset(lists):
    lists[0]=1000

myset = set()
mylist = list([100,2,3])
myset.update(mylist)
a = myset.pop()
myset.clear()
if myset:
    print('22')
else:
    print('clear')

clear


In [14]:
myset = set()
mylist = list([100,2,3,1])
myset.update(mylist)
print(next(iter(mylist)),next(iter(myset)),next(iter(myset)))


100 1 1


In [7]:
%reload_ext autoreload
%autoreload 2

In [7]:
os.getcwd(),os.pardir
dicts = {1:2,100:3,3:4}
sorted(dicts.items(),key=lambda x:x[0])

[(1, 2), (3, 4), (100, 3)]

## 测试Main 

In [ ]:
import os
import sys
sys.path.append(os.pardir)
from data.loader import InstanceConfigLoader
from framework.algorithm import ThresholdFirstFitAlgorithm,SchdeulerPolicyAlgorithm
from framework.instance import InstanceConfig
from framework.machine import MachineConfig
from framework.simulation import Simulation
from framework.trigger import ThresholdTrigger

import json

# res_struct_filename = os.path.join(os.getcwd(),'struct.json')
instance_number = 20
machine_number = int(instance_number/2+instance_number/4)
machine_configs = []
for id in range(machine_number):
    machine = MachineConfig(id,300,20,20)
    machine_configs.append(machine)
macFile = '/Users/lsh/Documents/ecnuIcloud/Trace/alibaba_2018/intp_dir'
windowsFile = 'D:\Data\workplace\ecnuicloud\Traces\intp_dir\\'
linux_file = '/hdd/sxy/Trace_alibaba2018/alibaba_2018/intp_dir'
instance_configs = InstanceConfigLoader(linux_file,instance_number)
sim = Simulation(machine_configs, instance_configs, ThresholdTrigger(), ThresholdFirstFitAlgorithm(),SchdeulerPolicyAlgorithm())
sim.run()

print(sim.cluster.structure)
# struct = sim.cluster.structure
# with open(res_struct_filename,'w') as file_job:
#     json.dump(struct,file_job)

## 测试SXY

In [12]:
import numpy as np
x = np.empty(shape=[1,5])
x= np.zeros(shape=(5))
cpu = np.random.randint(0,10,(4,3))

In [13]:
cost_min = 0
W = 3
print(cpu)
for t in range(W):
    cpu_t = cpu[:, t] # 提取cpu矩阵中第t-1列，比如t=0即提取下一时刻各VM的cpu需求量
    print(cpu_t)

[7 4 0 2]
[1 5 3 0]
[1 2 7 6]


## 测试python多态


In [ ]:
from abc import ABC, abstractmethod
class Algorithm(ABC):
    @abstractmethod
    def __call__(self, *args):
        pass

class ThresholdFirstFitAlgorithm(Algorithm):
    def __call__(self, cluster, clock):
        print('there is ThresholdFirstFitAlgorithm')
class RandomSampleAlgorithm(Algorithm):
    def __call__(self, cluster:list,env,lis):
        print('there is Random sample')
def test(algo):
    algo('1','2')
test(ThresholdFirstFitAlgorithm())
test(RandomSampleAlgorithm())

# 多资源测试


In [29]:
import os 
import pandas as pd
filepath = '/hdd/jbinin/alibaba2018_data_extraction/data/hole'
def read_list():
    files = os.listdir(filepath)
    for file in files:
        with open(file) as f:
            cpus = pd.read_csv(f)
            print(cpus)
def read_iterator(filepath):
    i = 0
    with os.scandir(filepath) as entries:
        for entry in entries:
            if entry.is_file():
                filename = os.path.join(filepath, entry.name)
                #print(filename)
                with open(filename) as f:
                    cpus = pd.read_csv(f,header=None)
                    return cpus[0].values.squeeze().tolist(),cpus[1].values.squeeze().tolist()

cpus,mem  = read_iterator(filepath)

In [7]:

%reload_ext autoreload
%autoreload 2

### main 测试

In [12]:
import json
import sys
sys.path.append('./Scheduler')
from data.loader import InstanceConfigLoader
from framework.algorithm import ThresholdFirstFitAlgorithm,SchdeulerPolicyAlgorithm
from framework.machine import MachineConfig
from framework.simulation import Simulation
from framework.trigger import ThresholdTrigger
def simple_test(filepath):
    # 测试用
    instance_number = 20
    machine_number = int(instance_number/2+instance_number/4)
    machine_configs = []
    for id in range(machine_number):
        machine = MachineConfig(id,300,20,20)
        machine_configs.append(machine)
    
    instance_configs = InstanceConfigLoader(filepath,instance_number)
    return instance_configs
def test_all(filepath):
    machine_number = 4034
    machine_configs = []
    for id in range(machine_number):
        machine = MachineConfig(id,100,100,100)
        machine_configs.append(machine)
    instance_configs = InstanceConfigLoader(filepath)
    return instance_configs
filepath = '/hdd/jbinin/alibaba2018_data_extraction/data/hole'
#test_all(filepath)
instance_configs = test_all(filepath)

0 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_70769.csv , 8639
1 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_68923.csv , 8639
2 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_55527.csv , 8639
3 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_39415.csv , 8639
4 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_30287.csv , 8639
5 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_63765.csv , 8639
6 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_32620.csv , 8639
7 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_58126.csv , 8639
8 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_17392.csv , 8639
9 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_28808.csv , 8639
10 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_9128.csv , 8639
11 , /hdd/jbinin/alibaba2018_data_extraction/data/hole/instanceid_40711.csv , 8639
12 , /hdd/jbini

In [ ]:
sim = Simulation(machine_configs, instance_configs, ThresholdTrigger(), ThresholdFirstFitAlgorithm(),SchdeulerPolicyAlgorithm())
sim.run()